services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fastcart-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 

  postgres-auth:
    image: postgres:15-alpine
    container_name: fastcart-db-auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fastcart_auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15-alpine
    container_name: fastcart-db-product
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fastcart_product
    ports:
      - "5434:5432" 
    volumes:
      - postgres_product_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15-alpine
    container_name: fastcart-db-order
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fastcart_order
    ports:
      - "5435:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  postgres-payment:
    image: postgres:15
    container_name: fastcart-db-payment
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fastcart_payment
    ports:
      - "5436:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data

  postgres-review:
    image: postgres:15
    container_name: fastcart-db-review
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fastcart_review
    ports:
      - "5437:5432"
    volumes:
      - postgres_review_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: fastcart-auth
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - postgres-auth
      

  product-service:
    build:
      context: ./services/product
      dockerfile: Dockerfile
      additional_contexts:
        shared_ctx: ./shared 
    container_name: fastcart-product
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - postgres-product
      - rabbitmq


  order-service:
    build:
      context: ./services/order
      dockerfile: Dockerfile
      additional_contexts:
        shared_ctx: ./shared     
    container_name: fastcart-order
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - postgres-order
      - rabbitmq
  gateway-service:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: fastcart-gateway
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - auth-service
      - product-service
      - order-service

  fastcart-payment:
    build:
      context: ./services/payment
      additional_contexts:
        shared_ctx: ./shared
    container_name: fastcart-payment
    ports:
      - "8005:8005"
    depends_on:
      - postgres-payment
      - rabbitmq
    env_file:
      - .env

  fastcart-review:
    build:
      context: ./services/review
      additional_contexts:
        shared_ctx: ./shared
    container_name: fastcart-review
    ports:
      - "8006:8006"
    depends_on:
      - postgres-review
    env_file:
      - .env

volumes:
  postgres_auth_data:
  postgres_product_data:
  postgres_order_data:
  postgres_payment_data:
  postgres_review_data:
