apiVersion: v1
kind: Service
metadata:
  name: fastcart-auth  
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP