apiVersion: v1
kind: Service
metadata:
  name: fastcart-order
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP