apiVersion: v1
kind: Service
metadata:
  name: fastcart-payment
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP