apiVersion: v1
kind: Service
metadata:
  name: fastcart-product
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP