apiVersion: v1
kind: Service
metadata:
  name: fastcart-review
  labels:
    app: review
spec:
  selector:
    app: review
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP