apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  labels:
    app: postgres
data:
  init.sql: |
    CREATE DATABASE fastcart_auth;
    CREATE DATABASE fastcart_product;
    CREATE DATABASE fastcart_order;
    CREATE DATABASE fastcart_payment;
    CREATE DATABASE fastcart_review;