name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, product, order, payment, review, cart]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Building fastcart-${{ matrix.service }}..."
          docker build \
            -t fastcart-${{ matrix.service }}:${{ github.sha }} \
            --build-context shared_ctx=./shared \
            ./services/${{ matrix.service }}

      - name: Save Docker Image to Tarball
        run: |
          docker save fastcart-${{ matrix.service }}:${{ github.sha }} > fastcart-${{ matrix.service }}.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.service }}
          path: fastcart-${{ matrix.service }}.tar
          retention-days: 1 


  push:
    name: Push to Artifact Registry
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    strategy:
      matrix:
        service: [auth, product, order, payment, review, cart]
        
    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-${{ matrix.service }}

      - name: Load Docker Image
        run: |
          docker load < fastcart-${{ matrix.service }}.tar

      - name: Authenticate to Google Cloud via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Tag and Push Docker Image
        run: |
          IMAGE_URL=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/fastcart-${{ matrix.service }}
          
          echo "Tagging and pushing to $IMAGE_URL..."
          
          docker tag fastcart-${{ matrix.service }}:${{ github.sha }} $IMAGE_URL:${{ github.sha }}
          docker tag fastcart-${{ matrix.service }}:${{ github.sha }} $IMAGE_URL:latest
          
          docker push $IMAGE_URL:${{ github.sha }}
          docker push $IMAGE_URL:latest
  update-gitops:
    name: Update ArgoCD Manifests
    needs: push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: 'milospejic/fastcart-k8s'
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-repo

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        
      - name: Update Image Tags with new SHA
        working-directory: gitops-repo/overlays/prod
        run: |
          BASE_URL="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}"
          
          kustomize edit set image fastcart-auth=$BASE_URL/fastcart-auth:${{ github.sha }}
          kustomize edit set image fastcart-product=$BASE_URL/fastcart-product:${{ github.sha }}
          kustomize edit set image fastcart-order=$BASE_URL/fastcart-order:${{ github.sha }}
          kustomize edit set image fastcart-payment=$BASE_URL/fastcart-payment:${{ github.sha }}
          kustomize edit set image fastcart-review=$BASE_URL/fastcart-review:${{ github.sha }}
          kustomize edit set image fastcart-cart=$BASE_URL/fastcart-cart:${{ github.sha }}
      
      - name: Commit and Push to GitOps Repo
        working-directory: gitops-repo
        run: |
          git config user.name "GitHub Actions CI"
          git config user.email "actions@github.com"
          
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add overlays/prod/kustomization.yml
            git commit -m "chore: deploy new image tags [SHA: ${{ github.sha }}]"
            git push
          fi